# Generated by Django 4.2.7 on 2023-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='contador',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
