# Generated by Django 4.2.7 on 2023-11-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_contador_carrito_contador_productos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='contador_productos',
            new_name='pInC',
        ),
        migrations.DeleteModel(
            name='SolicitudCompra',
        ),
    ]
