# Generated by Django 4.2.7 on 2023-11-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_contador_productos_carrito_pinc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
