# Generated by Django 4.2.7 on 2023-11-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_solicitud_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='productos',
            field=models.JSONField(default=''),
        ),
    ]
