# Generated by Django 4.2.7 on 2023-11-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_solicitud_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='productos',
            field=models.ManyToManyField(through='myapp.ItemSolicitud', to='myapp.producto'),
        ),
    ]
